<a href="https://colab.research.google.com/github/lavarius/CrimeAnalytics/blob/main/SF_Crime_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import requests
import pandas as pd

In [3]:
# Define the API endpoint
url = "https://data.sfgov.org/resource/wg3w-h783.json"
# Make a GET request to fetch the raw data
response = requests.get(url)
# Parse the JSON data
data = response.json()
# Convert the JSON data to a DataFrame
crime = pd.DataFrame(data)

In [4]:
crime.head()

,incident_datetime,incident_date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,report_type_code,...,supervisor_district_2012,latitude,longitude,point,:@computed_region_26cr_cadq,:@computed_region_qgnn_b9vv,:@computed_region_jwn9_ihcz,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_n4xg_c4py
0,2023-03-13T23:41:00.000,2023-03-13T00:00:00.000,23:41,2023,Monday,2023-03-13T23:41:00.000,125373607041,1253736,230167874,VS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-03-01T05:02:00.000,2023-03-01T00:00:00.000,05:02,2023,Wednesday,2023-03-11T15:40:00.000,125379506374,1253795,236046151,II,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-03-13T13:16:00.000,2023-03-13T00:00:00.000,13:16,2023,Monday,2023-03-13T13:17:00.000,125357107041,1253571,220343896,VS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-03-13T10:59:00.000,2023-03-13T00:00:00.000,10:59,2023,Monday,2023-03-13T11:00:00.000,125355107041,1253551,230174885,VS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-03-14T18:44:00.000,2023-03-14T00:00:00.000,18:44,2023,Tuesday,2023-03-14T18:45:00.000,125402407041,1254024,230176728,VS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
crime.columns

Index(['incident_datetime', 'incident_date', 'incident_time', 'incident_year',
       'incident_day_of_week', 'report_datetime', 'row_id', 'incident_id',
       'incident_number', 'report_type_code', 'report_type_description',
       'incident_code', 'incident_category', 'incident_subcategory',
       'incident_description', 'resolution', 'police_district', 'filed_online',
       'cad_number', 'intersection', 'cnn', 'analysis_neighborhood',
       'supervisor_district', 'supervisor_district_2012', 'latitude',
       'longitude', 'point', ':@computed_region_26cr_cadq',
       ':@computed_region_qgnn_b9vv', ':@computed_region_jwn9_ihcz',
       ':@computed_region_h4ep_8xdi', ':@computed_region_nqbw_i6c3',
       ':@computed_region_n4xg_c4py'],
      dtype='object')